name: Continuous Integration

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_win:
    name: Build on Windows
    runs-on: windows-2016
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build OGS5
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --config Release -j

      - uses: actions/upload-artifact@v2
        with:
          path: ./build/bin/*
